import { type NextPage } from "next";
import Head from "next/head";

const Mission: NextPage = () => {
  const title = 'Mission';

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b text-lg text-pink-300 from-[#ffffff] to-[#333333]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-violet-200 sm:text-[5rem]">
            {title}
          </h1>
          <div>
            <p>At Flight Search Companion, we are dedicated to helping you find the best flights for your travel needs. Our innovative platform uses cutting-edge technology to simplify the process of searching and booking flights, so you can focus on enjoying your trip.</p>
            <ul className="list-decimal">
              <li>Personalized Recommendations: Our AI-powered system uses your travel history and preferences to provide you with personalized recommendations for flights.</li>
              <li>Time-Saving Features: With our intuitive interface and automated processes, you can save time and hassle by easily finding and booking the best flight options for your needs.</li>
              <li>Cost Savings: We use advanced algorithms to find the best deals and discounts on flights, so you can save money on your trip.</li>
              <li>24/7 Customer Support: Our dedicated customer support team is available 24/7 to assist you with any questions or issues you may have before, during, or after your trip.</li>
              <li>Seamless Integration: Our platform seamlessly integrates with popular travel booking sites and services, so you can easily compare prices and options and book your flight plans in one place.</li>
            </ul>
            <p>At Flight Search Companion, our mission is to make flight searching and booking easier, more efficient, and more enjoyable than ever before. With our innovative AI tools and commitment to exceptional customer service, we're confident that we can help you find and book the perfect flight every time.</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Mission;